### PR TITLE
Include template files

### LINKED ISSUE #71: fail to create new game after deleting tool source
When I executed the ‘amethyst new’ command, the tool successfully created a new folder, but the creation of the new game project failed, the details are as follows：

lws@lws-deepin:/tool/project/games$ RUST_BACKTRACE=1 amethyst new pong -a 0.10.0
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', libcore/result.rs:1009:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:476
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   6: rust_begin_unwind
             at libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   8: core::result::unwrap_failed
   9: std::sync::once::Once::call_once::{{closure}}
  10: std::sync::once::Once::call_inner
             at libstd/sync/once.rs:397
  11: amethyst_cli::templates::deploy
  12: amethyst_cli::new::New::execute
  13: amethyst::main
  14: std::rt::lang_start::{{closure}}
  15: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  16: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  17: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  18: main
  19: __libc_start_main
  20: _start

### PR DESCRIPTION
**Pull request by BradLugo**
This PR adds the build script functionality back and changes `deploy` to use the included files.

Note that the build script doesn't account for different templates, only `main` templates.  Thus, `deploy` doesn't change its behavior based on the `template` parameter. I'll open an issue to add functionality to determine more templates if and when this PR is merged.

Closes #71

### CODE REVIEW

**Comment by BradLugo** [comment]
This is the first time I've written Rust. I'm open to suggestions and feedback, even if it's simply idiomatic changes.

File: build.rs [hunk 1]
```diff
@@ -0,0 +1,56 @@
+//! Reads the `templates/` directory and includes all versions' templates as
+//! part of the binary to reduce installation footprint
+extern crate ron;
```
Comment (torkleyy) [inline build.rs:3]: `extern crate` is not required in Rust 2018.

File: build.rs [hunk 2]
```diff
@@ -0,0 +1,56 @@
...
+use std::io::Write;
+use std::path::{Path, PathBuf};
+
+use ron::de::from_reader;
+
+fn path(env: &str, s: &str) -> PathBuf {
+    PathBuf::from(env::var(env).unwrap()).join(s)
+}
+
+fn read_template_index<P: AsRef<Path>>(p: P) -> Vec<String> {
```
Comment (torkleyy) [inline build.rs]: This should probably take `P: Into<PathBuf>` and use `p.into()` below to create the `PathBuf`.

**Review by torkleyy — COMMENTED** [review]
Thank you @BradLugo! Looks pretty good, I just have two comments.

File: build.rs (hunk 1 above)
Comment (BradLugo) [reply build.rs:3]: If I remove this, the build throws the following errors:
```
error[E0433]: failed to resolve: maybe a missing `extern crate ron;`?
 --> build.rs:8:5
  |
8 | use ron::de::from_reader;
  |     ^^^ maybe a missing `extern crate ron;`?

error[E0425]: cannot find function `from_reader` in this scope
  --> build.rs:18:5
   |
18 |     from_reader(File::open(&path).expect("Failed to open index.ron"))
   |     ^^^^^^^^^^^ not found in this scope
```

If I add `edition = "2018"` to `Cargo.toml`, the build throws a ton more errors

Comment (torkleyy) [reply build.rs:3]: Oh I see, we haven't upgraded yet! Never mind then.

**Comment by torkleyy** [comment]
https://travis-ci.org/amethyst/tools/jobs/545270691#L635 - liquid doesn't build anymore.

File: build.rs (hunk 1 above)
Comment (BradLugo) [reply build.rs]: I can open an issue to do a general upgrade. Looks like the build's been failing due to the old liquid package. I can encompass this along with an other packages that might break the build.

**Comment by torkleyy** [comment]
also see https://github.com/rust-lang/rust/issues/60958#issuecomment-498084664

**Comment by BradLugo** [comment]
Is this blocking the PR? I can look into liquid's repo and see if this is an issue in the current version, and I can open an issue to do a general upgrade for this project, moving to Rust 2018 and upgrading the other packages. I can encompass the liquid build issue along with any other packages that might break the build.

**Comment by torkleyy** [comment]
It's failing CI, but I guess I can merge like this.
